# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default_twitter: &default_twitter
  twitter_api_key: <%= ENV["TWITTER_CONSUMER_KEY_DEV"] %>
  twitter_api_secret: <%=ENV["TWITTER_CONSUMER_SECRET_DEV"] %>
  twitter_login_key: <%=ENV["TWITTER_LOGIN_KEY"] %>
  twitter_login_secret: <%=ENV["TWITTER_LOGIN_SECRET"] %>

default_facebook: &default_facebook
  facebook_api_key: <%= ENV["FACEBOOK_CONSUMER_KEY_DEV"] %>
  facebook_api_secret: <%=ENV["FACEBOOK_CONSUMER_SECRET_DEV"] %>
  facebook_login_key: <%=ENV["FACEBOOK_LOGIN_KEY"] %>
  facebook_login_secret: <%=ENV["FACEBOOK_LOGIN_SECRET"] %>

default_google: &default_google
  google_api_key: <%= ENV["GOOGLE_CONSUMER_KEY_DEV"] %>
  google_api_secret: <%=ENV["GOOGLE_CONSUMER_SECRET_DEV"] %>
  google_login_key: <%=ENV["GOOGLE_LOGIN_KEY"] %>
  google_login_secret: <%=ENV["GOOGLE_LOGIN_SECRET"] %>

default_amazon_aws_s3: &default_amazon_aws_s3
  aws_access_key_id: <%=ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%=ENV["AWS_SECRET_ACCESS_KEY"] %>

default_mailer: &default_mailer
  gmail_account_id: <%= ENV["SMTP_GMAIL_ID"] %>
  gmail_account_secret: <%= ENV["SMTP_GMAIL_SECRET"] %>

development:
  secret_key_base: 73ca84fa2c5ff78a0f75fffccf504c4fba3b4b4de016ed60ef015652282a18617ae4f9b43175c2a1a2e37cc54589322051dde58864c28121d03dad5e92057dad
  <<: *default_twitter
  <<: *default_facebook
  <<: *default_google
  <<: *default_amazon_aws_s3
  <<: *default_mailer
  
test:
  secret_key_base: fb2ff8dfa06f47445acbb324bde558be49bdb26e4be70049606b8910a768ccb4d03cdb7c765b18a571c7e82873508efed2de4d00dd00e8bed35b891025ca7f84
  <<: *default_twitter
  <<: *default_facebook
  <<: *default_google
  <<: *default_amazon_aws_s3
  <<: *default_mailer
  
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  
  twitter_api_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_api_secret: <%=ENV["TWITTER_CONSUMER_SECRET"] %>
  twitter_login_key: <%=ENV["TWITTER_LOGIN_KEY"] %>
  twitter_login_secret: <%=ENV["TWITTER_LOGIN_SECRET"] %>
  
  facebook_api_key: <%= ENV["FACEBOOK_CONSUMER_KEY"] %>
  facebook_api_secret: <%=ENV["FACEBOOK_CONSUMER_SECRET"] %>
  facebook_login_key: <%=ENV["FACEBOOK_LOGIN_KEY"] %>
  facebook_login_secret: <%=ENV["FACEBOOK_LOGIN_SECRET"] %>

  google_api_key: <%= ENV["GOOGLE_CONSUMER_KEY"] %>
  google_api_secret: <%=ENV["GOOGLE_CONSUMER_SECRET"] %>
  google_login_key: <%=ENV["GOOGLE_LOGIN_KEY"] %>
  google_login_secret: <%=ENV["GOOGLE_LOGIN_SECRET"] %>

  aws_access_key_id: <%=ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%=ENV["AWS_SECRET_ACCESS_KEY"] %>
  
  gmail_account_id: <%= ENV["SMTP_GMAIL_ID"] %>
  gmail_account_secret: <%= ENV["SMTP_GMAIL_SECRET"] %>
