# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default_twitter: &default_twitter
  twitter_api_key: 'OJeenwU9UGyZBgfQe15q5SQFx'
  twitter_api_secret: 'rtOXkxIpjyT1sRI7gYUeEbiyHzYZgp1R2spyjrc8WBJ6VfYUFf'
  twitter_login_key: 'twitter@account.user'
  twitter_login_secret: 'twitter'
  
default_facebook: &default_facebook
  facebook_api_key: '1451267615011846'
  facebook_api_secret: '98caf58ea971e6df9c9b52fe19eb47fd'
  facebook_login_key: 'facebook@account.user'
  facebook_login_secret: 'facebook'

default_google: &default_google
  google_api_key: '728594831656-9lu6jardbec2231b0ousc0mo1v5bds7r.apps.googleusercontent.com'
  google_api_secret: 'A3UnrzkC2aaSGIeceoLIUVd-'
  google_login_key: 'google@account.user'
  google_login_secret: 'google'
 
development:
  secret_key_base: 73ca84fa2c5ff78a0f75fffccf504c4fba3b4b4de016ed60ef015652282a18617ae4f9b43175c2a1a2e37cc54589322051dde58864c28121d03dad5e92057dad
  <<: *default_twitter
  <<: *default_facebook
  <<: *default_google
  
test:
  secret_key_base: fb2ff8dfa06f47445acbb324bde558be49bdb26e4be70049606b8910a768ccb4d03cdb7c765b18a571c7e82873508efed2de4d00dd00e8bed35b891025ca7f84
  <<: *default_twitter
  <<: *default_facebook
  <<: *default_google
  
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  
  twitter_api_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_api_secret: <%=ENV["TWITTER_CONSUMER_SECRET"] %>
  twitter_login_key: <%=ENV["TWITTER_LOGIN_KEY"] %>
  twitter_login_secret: <%=ENV["TWITTER_LOGIN_SECRET"] %>
  
  facebook_api_key: <%= ENV["FACEBOOK_CONSUMER_KEY"] %>
  facebook_api_secret: <%=ENV["FACEBOOK_CONSUMER_SECRET"] %>
  facebook_login_key: <%=ENV["FACEBOOK_LOGIN_KEY"] %>
  facebook_login_secret: <%=ENV["FACEBOOK_LOGIN_SECRET"] %>

  google_api_key: <%= ENV["GOOGLE_CONSUMER_KEY"] %>
  google_api_secret: <%=ENV["GOOGLE_CONSUMER_SECRET"] %>
  google_login_key: <%=ENV["GOOGLE_LOGIN_KEY"] %>
  google_login_secret: <%=ENV["GOOGLE_LOGIN_SECRET"] %>
